<?php

return [
    'smashed-avo-chilli' => [
        'title' => 'Smashed Avo with Chilli Flakes',
        'slug' => 'smashed-avo-chilli',
        'category' => 'brunch',
        'time' => '5 mins',
        'difficulty' => 'Easy',
        'description' => 'The classic. Creamy avocado, a squeeze of lime, red chilli flakes, and flaky sea salt on thick sourdough. Simple, perfect, iconic.',
        'hero_color' => '#4a7c59',
        'ingredients' => [
            '2 slices thick-cut sourdough',
            '1 ripe avocado',
            '1/2 lime, juiced',
            'Red chilli flakes',
            'Flaky sea salt',
            'Extra virgin olive oil',
            'Optional: poached egg',
        ],
        'steps' => [
            'Toast your sourdough until golden and crispy on the outside, chewy inside.',
            'Halve the avocado, remove the stone, and scoop into a bowl.',
            'Smash with a fork — keep it chunky, not smooth. Squeeze in the lime juice.',
            'Pile the smashed avo onto your toast generously.',
            'Drizzle with olive oil, scatter chilli flakes, and finish with flaky sea salt.',
            'Add a poached egg on top if you\'re feeling fancy.',
        ],
        'tip' => 'The avocado should be ripe but not mushy. If it\'s brown inside, start over — life\'s too short for sad avo.',
    ],
    'ricotta-honey-fig' => [
        'title' => 'Ricotta, Honey & Fig',
        'slug' => 'ricotta-honey-fig',
        'category' => 'sweet',
        'time' => '5 mins',
        'difficulty' => 'Easy',
        'description' => 'Creamy ricotta on warm toast, topped with ripe figs, a drizzle of honey, and crushed pistachios. Feels fancy, takes five minutes.',
        'hero_color' => '#8b5e83',
        'ingredients' => [
            '2 slices rustic bread or sourdough',
            '120g fresh ricotta',
            '2-3 fresh figs, quartered',
            '2 tbsp honey (runny)',
            '1 tbsp crushed pistachios',
            'Pinch of flaky sea salt',
        ],
        'steps' => [
            'Toast your bread until it has a good crunch.',
            'Spread a thick layer of ricotta on each slice.',
            'Arrange the fig quarters on top, pressing gently into the ricotta.',
            'Drizzle generously with honey.',
            'Scatter crushed pistachios and finish with a tiny pinch of flaky salt.',
        ],
        'tip' => 'No fresh figs? Use fig jam as a base layer under the ricotta. Different vibe, still incredible.',
    ],
    'peanut-butter-banana' => [
        'title' => 'PB, Banana & Cinnamon Crunch',
        'slug' => 'peanut-butter-banana',
        'category' => 'sweet',
        'time' => '3 mins',
        'difficulty' => 'Easy',
        'description' => 'Crunchy peanut butter, sliced banana, a dusting of cinnamon, and a drizzle of honey. The ultimate comfort toast — childhood you would be proud.',
        'hero_color' => '#b8860b',
        'ingredients' => [
            '2 slices thick white or wholemeal bread',
            '2 tbsp crunchy peanut butter',
            '1 banana, sliced',
            '1/2 tsp ground cinnamon',
            'Honey for drizzling',
            'Optional: granola for extra crunch',
        ],
        'steps' => [
            'Toast your bread until golden.',
            'Spread peanut butter generously while the toast is still warm (it\'ll get melty and amazing).',
            'Layer banana slices across the top.',
            'Dust with cinnamon and drizzle with honey.',
            'Scatter some granola on top if you want that extra crunch factor.',
        ],
        'tip' => 'Use a ripe banana — the sweeter the better. Green bananas on toast is a crime.',
    ],
    'garlic-mushroom-thyme' => [
        'title' => 'Garlic Mushrooms on Toast',
        'slug' => 'garlic-mushroom-thyme',
        'category' => 'savoury',
        'time' => '10 mins',
        'difficulty' => 'Easy',
        'description' => 'Buttery, garlicky mushrooms with fresh thyme piled on sourdough. Rich, earthy, and deeply satisfying. Proper comfort food.',
        'hero_color' => '#5c4033',
        'ingredients' => [
            '2 slices sourdough',
            '200g mixed mushrooms (chestnut, button, king oyster)',
            '2 cloves garlic, finely sliced',
            '2 tbsp butter',
            'Fresh thyme sprigs',
            'Salt and black pepper',
            'Optional: grated parmesan',
        ],
        'steps' => [
            'Slice mushrooms into thick pieces. Finely slice the garlic.',
            'Heat butter in a pan over medium-high heat until foaming.',
            'Add mushrooms in a single layer — don\'t crowd the pan. Let them get golden without stirring for 2-3 minutes.',
            'Flip, add garlic and thyme, cook another 2 minutes. Season generously.',
            'Toast your sourdough.',
            'Pile the mushrooms on top. Finish with parmesan and black pepper.',
        ],
        'tip' => 'The secret is NOT stirring the mushrooms. Let them sit and get properly golden before you touch them.',
    ],
    'burrata-tomato-basil' => [
        'title' => 'Burrata, Tomato & Basil Bruschetta',
        'slug' => 'burrata-tomato-basil',
        'category' => 'brunch',
        'time' => '8 mins',
        'difficulty' => 'Easy',
        'description' => 'Charred ciabatta, creamy burrata torn open, sweet cherry tomatoes, fresh basil, and the best olive oil you own. Summer on a plate.',
        'hero_color' => '#c0392b',
        'ingredients' => [
            '4 slices ciabatta, cut thick',
            '1 ball burrata (125g)',
            '200g cherry tomatoes, halved',
            'Fresh basil leaves',
            'Extra virgin olive oil (the good stuff)',
            'Balsamic glaze',
            'Flaky sea salt and black pepper',
            '1 clove garlic, halved',
        ],
        'steps' => [
            'Char the ciabatta slices under a grill or on a griddle pan until you get those gorgeous grill marks.',
            'While warm, rub each slice with the cut side of the garlic clove.',
            'Toss cherry tomatoes with a drizzle of olive oil, salt, and pepper.',
            'Place the burrata in the centre of a board, tear it open so the creamy inside spills out.',
            'Arrange the charred bread around it, pile on the tomatoes, scatter basil.',
            'Drizzle everything with olive oil and balsamic glaze.',
        ],
        'tip' => 'Let the burrata come to room temperature before serving. Cold burrata is a missed opportunity.',
    ],
    'cinnamon-french-toast' => [
        'title' => 'Classic Cinnamon French Toast',
        'slug' => 'cinnamon-french-toast',
        'category' => 'sweet',
        'time' => '15 mins',
        'difficulty' => 'Easy',
        'description' => 'Thick brioche soaked in vanilla cinnamon egg, pan-fried until golden, topped with maple syrup and berries. Weekend mornings were made for this.',
        'hero_color' => '#d4a017',
        'ingredients' => [
            '4 thick slices brioche or challah',
            '3 large eggs',
            '80ml whole milk',
            '1 tsp vanilla extract',
            '1 tsp ground cinnamon',
            '1 tbsp butter for frying',
            'Maple syrup',
            'Fresh berries',
            'Icing sugar for dusting',
        ],
        'steps' => [
            'Whisk eggs, milk, vanilla, and cinnamon together in a shallow bowl.',
            'Heat butter in a non-stick pan over medium heat.',
            'Dip each bread slice in the egg mixture, letting it soak for 10 seconds per side.',
            'Fry for 2-3 minutes per side until golden brown and slightly puffed.',
            'Stack on a plate, top with berries, dust with icing sugar, and drizzle with maple syrup.',
        ],
        'tip' => 'Day-old bread works best — it soaks up the egg without falling apart. Fresh bread can go soggy.',
    ],
];
